import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import SidebarMenu from '../components/sidebar-menu'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bodyStyle = {
  color: "var(--color-text)",
  backgroundColor: "var(--color-background)",
  fontFamily: "Arial",
  display: "flex",
  height: "100vh",
  margin: "0",
  padding: "0",
};

const mainStyle = {
  display:"block",
  backgroundColor: "transparent", //var(--color-background)",
  minHeight:"100vh",
  margin: "0 var(--size-30) var(--size-30) var(--size-30)"
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={bodyStyle}>
        <SidebarMenu />
        <main style={mainStyle}>{children}</main>
      </body>
    </html>
  );
}
